package com.web.ssm.dao;

import java.util.List;
import java.util.Map;

import com.web.ssm.pojo.Product;

public interface ProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	Product selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tbl_product
	 * @mbg.generated  Thu Sep 29 23:21:21 CST 2016
	 */
	int updateByPrimaryKey(Product record);
	
	List<Product> findProductBySellerId(Long seller_id);
	
	Product selectWithSellerById(Long id);
	
	Map<String, Object> selectMapById(Long id);
	
	List<Map<String, Object>> findMapBySellerId(Long sellerId);
}